#!/usr/bin/env bash

APP_DIR=$(pwd)
DATA_DIR="$APP_DIR/data"
mkdir -p "$DATA_DIR"
./generate-config "$DATA_DIR"

echo "Create symlink /usr/local/bin/oh-hai"
sudo ln -sf "$APP_DIR/oh-hai" /usr/local/bin/oh-hai

# for bash
FILE_BASHRC=~/.bashrc
if [ -f "$FILE_BASHRC" ]; then
  BASH_SCRIPT_KEYBINDING="$APP_DIR/shell/key-bindings.bash"
  RC_FILE="$DATA_DIR/.bash"
  tee "$RC_FILE" > /dev/null <<EOT
if [ -f '$BASH_SCRIPT_KEYBINDING' ]; then
. '$BASH_SCRIPT_KEYBINDING'
fi
EOT
  SOURCE_STR="[ -f $RC_FILE ] && source $RC_FILE"
  SOURCE_STR_ESCAPED=$(echo "$SOURCE_STR" | sed 's/[][\\.*^$\-\/]/\\&/g')
  if ! grep -q "^$SOURCE_STR_ESCAPED" $FILE_BASHRC ; then
    printf "\n$SOURCE_STR" >> $FILE_BASHRC
  fi
else
  echo "warn: $FILE_BASHRC does not exist."
fi

echo 'Successfully installed'
echo 'Restart shell or reload bin file.'
